ALTER TABLE t_p10348444_project_alpha_creati.users
  ADD COLUMN IF NOT EXISTS playtime_minutes INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS blocks_mined INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS kills INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS deaths INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_seen TIMESTAMP,
  ADD COLUMN IF NOT EXISTS join_date TIMESTAMP DEFAULT NOW();
